apiVersion: apps/v1
kind: Deployment

metadata:
  name: rolling-demo

spec:

  replicas: 4

  strategy:

    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: rolling-demo

  template:

    metadata:
      labels:
        app: rolling-demo

    spec:

      containers:

      - name: app

        image: yashamin62/devops-module12:2

        env:

        - name: VERSION
          value: "v1"

        - name: FEATURE_ENABLED
          value: "false"

        ports:
        - containerPort: 3000
